services:
  backup:
    image:  ghcr.io/vkoop/docker-simplebackup:master
    volumes:
      - "backup:/backups"
      - "config:/backup-script/config"
      - "ssh:/ssh"
    restart: "no"
    command: ["echo", "Backup container is scheduled by Ofelia and will not run continuously"]
    
  # Ofelia scheduler container
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - backup
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    labels:
      # Run backup daily at 2 AM
      ofelia.job-run.backup.schedule: "0 0 2 * * *"
      ofelia.job-run.backup.container: "server_backup"
      ofelia.job-run.backup.command: "backup"
volumes:
  config:
    external: true
    name: server_backup_config
  ssh:
    external: true
    name: server_backup_ssh
  backup:
    name: server_backup
    external: true

